# Generated by Django 5.2.11 on 2026-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
